site_name: IBM Automation - Event-driven Solution - Sharing knowledge
site_description: IBM Automation - Event-Driven Solution - Sharing knowledge
repo_url: https://github.com/ibm-cloud-architecture/refarch-eda
docs_dir: docs-mk
site_dir: public
edit_uri: edit/master/docs-mk
theme: 
  name: material
  logo: images/es-icon.png
  feature:
    tabs: true
  palette:
    scheme: default
    primary: 'black'
  language: en
  custom_dir: overrides
  features:
      - navigation.tabs
      - navigation.instant
      - navigation.tracking
      - navigation.tabs.sticky
      - navigation.top
  social:
    - type: 'github'
      link: 'https://github.com/ibm-cloud-architecture'
# Copyright
copyright: Copyright © 2022  IBM
extra_css: ["extra.css"]
use_directory_urls: true
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
      
markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs-mk/snippets
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.escapeall
  

nav:
  - Introduction:
    - Overview: introduction/overview/index.md
    - Advantages of EDA:
      - Microservice decoupling: /advantages/microservice
      - Reactive systems: /advantages/reactive/
      - Resiliency: /advantages/resiliency/
      - Scalability: /advantages/scalability/
  - Technology:
    - Kafka Consumers: /technology/kafka-consumers
    - Kafka Streams: /technology/kafka-streams
    - Mirror Maker 2:  /technology/kafka-mirrormaker
